package com.rxnews.greendao;

import android.database.sqlite.SQLiteDatabase;

import java.util.Map;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.AbstractDaoSession;
import de.greenrobot.dao.identityscope.IdentityScopeType;
import de.greenrobot.dao.internal.DaoConfig;

import com.rxnews.greendao.Greenrxnews;

import com.rxnews.greendao.GreenrxnewsDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see de.greenrobot.dao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig greenrxnewsDaoConfig;

    private final GreenrxnewsDao greenrxnewsDao;

    public DaoSession(SQLiteDatabase db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        greenrxnewsDaoConfig = daoConfigMap.get(GreenrxnewsDao.class).clone();
        greenrxnewsDaoConfig.initIdentityScope(type);

        greenrxnewsDao = new GreenrxnewsDao(greenrxnewsDaoConfig, this);

        registerDao(Greenrxnews.class, greenrxnewsDao);
    }
    
    public void clear() {
        greenrxnewsDaoConfig.getIdentityScope().clear();
    }

    public GreenrxnewsDao getGreenrxnewsDao() {
        return greenrxnewsDao;
    }

}
